api: 1.13.2-R0.1-SNAPSHOT
api-version: "1.13"
main: dev.buha007.spigot.simplelootchests.SimpleLootChests
name: SimpleLootChests
version: "2.0"
author: Bufnita
commands:
  slc:
    description: main command
    usage: /slc <args>